---
language: python
services: docker

env:
  global:
    - ROLE_NAME: kamailio
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

matrix:
  allow_failures:
    - env: MOLECULE_DISTRO=debian10
    - env: MOLECULE_DISTRO=ubuntu1804

install:
  # Install test dependencies.
  - pip install testinfra molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - cd ansible-$ROLE_NAME-mw

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
