---
- name: Install gpg package
  apt:
    name: gnupg
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add kamailio Repo Signing key
  apt_key:
    url: "{{ kamailio_repo_key_url }}"
    state: present
  when: kamailio_manage_repo

- name: Add kamailio apt repository
  apt_repository:
    repo: deb {{ kamailio_repo }}{{ kamailio_version }} {{ debian_version }} main
    state: present
    filename: 'kamailio'
  when: kamailio_manage_repo

- name: Add kamailio apt source repository
  apt_repository:
    repo: deb-src {{ kamailio_repo }}{{ kamailio_version }} {{ debian_version }} main
    state: present
    filename: 'kamailio'
  when: kamailio_manage_repo

- name: Update APT Cache
  apt: update_cache=yes
  when: kamailio_manage_repo

- name: Install kamailio
  apt:
    name: "{{ kamailio_packages }}"
    state: latest
  notify: Restart kamailio

- name: Copy kamailio configuration files.
  template:
    src: "{{ kamailio_config_template_dir }}/{{ item }}.j2"
    dest: "{{ kamailio_conf_dir }}/{{ item }}"
    backup: true
  with_items: "{{ kamailio_config_files }}"
  notify: Restart kamailio
  when: kamailio_install_conf

- name: Make sure kamailio is started and configure it to run at boot.
  service: name=kamailio enabled=yes

- name: Inject PGSQL password
  delegate_to: "{{ kamailio_creatordb_host }}"
  template:
    src: templates/pgpass
    dest: ~/.pgpass
    mode: 0600
  when: kamailio_create_db and kamailio_db_engine == 'PGSQL'

- name: Create Kamailio DB using kamdbctl create
  delegate_to: "{{ kamailio_creatordb_host }}"
  command: kamdbctl create
  run_once: true
  notify: Restart kamailio
  when: kamailio_create_db and kamailio_db_engine == 'PGSQL'

- name: Install pexpect
  pip:
    name: pexpect
  when: kamailio_create_db and kamailio_db_engine == 'MYSQL'

- name: Create Kamailio DB using kamdbctl create
  delegate_to: "{{ kamailio_creatordb_host }}"
  expect:
    command: kamdbctl create
    responses:
      password: "{{ kamailio_db_root_pass }}"
      (?i)Install: "y"
  run_once: true
  notify: Restart kamailio
  when: kamailio_create_db and kamailio_db_engine == 'MYSQL'
